import string

DIGITS = '0123456789'
LETTERS = string.ascii_letters
LETTER_DIGITS = LETTERS + DIGITS

TT_INT = 'INT'
TT_FLOAT = 'FLOAT'
TT_STRING = 'STRING'
TT_IDENTIFIER = 'NAME'
TT_KEYWORD = 'KEYWORD'
TT_PLUS = 'PLUS'
TT_MINUS = 'MINUS'
TT_MUL = 'MUL'
TT_DIV = 'DIV'
TT_EQ = 'ASSIGN'
TT_LPAREN = 'LPAREN'
TT_RPAREN = 'RPAREN'
TT_LSQUARE = 'LSQUARE'
TT_RSQUARE = 'RSQUARE'
TT_EE = 'EQUAL'
TT_NE = 'NOT_EQUAL'
TT_LT = 'LESS'
TT_GT = 'GREATER'
TT_LTE = 'LESS_EQUAL'
TT_GTE = 'GREATER_EQUAL'
TT_EOF = 'EOF'
TT_COMMA = 'COMMA'
TT_ARROW = 'ARROW'

KEYWORDS = [
    'THANG',
    "AN'",
    'OR',
    "AIN'T",
    'RECKON',
    'THEN',
    'MIGHTCOULD',
    'ELSE',
    'TROT',
    "T'",
    'BY_A_PEICE',
    "FIXIN'",
    'WHILES'
]